// monitor/src/solanaSubmitter.ts
//
// Submits the SP1 proof to Solana and queues the Arcium MXE computation.
// Uses the Arcium TypeScript client for encryption.

import {
  Connection,
  Keypair,
  PublicKey,
  SystemProgram,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import * as anchor from "@coral-xyz/anchor";
import {
  RescueCipher,
  getMXEPublicKey,
  getArciumEnv,
  awaitComputationFinalization,
  x25519,
  deserializeLE,
} from "@arcium-hq/client";
import { randomBytes } from "crypto";
import * as fs from "fs";
import { logger } from "./logger";
import { config } from "./config";
import { GeneratedProof } from "./proofGenerator";
import { ActiveRule } from "./ethWatcher";

// IDL imports (generated by `anchor build`)
import RegistryIDL from "../../target/idl/prova_registry.json";
import ExecutorIDL from "../../target/idl/prova_executor.json";

export class SolanaSubmitter {
  private connection: Connection;
  private monitorKeypair: Keypair;
  private provider: anchor.AnchorProvider;
  private registryProgram: anchor.Program;
  private executorProgram: anchor.Program;

  constructor() {
    this.connection = new Connection(config.solanaRpcUrl, "confirmed");

    // Load monitor keypair from disk
    const rawKp = JSON.parse(
      fs.readFileSync(config.monitorKeypairPath, "utf8"),
    );
    this.monitorKeypair = Keypair.fromSecretKey(Uint8Array.from(rawKp));

    const wallet = new anchor.Wallet(this.monitorKeypair);
    this.provider = new anchor.AnchorProvider(this.connection, wallet, {
      commitment: "confirmed",
    });
    anchor.setProvider(this.provider);

    this.registryProgram = new anchor.Program(
      RegistryIDL as anchor.Idl,
      new PublicKey(config.registryProgramId),
      this.provider,
    );

    this.executorProgram = new anchor.Program(
      ExecutorIDL as anchor.Idl,
      new PublicKey(config.executorProgramId),
      this.provider,
    );
  }

  /**
   * Full submission flow:
   *   1. Mark rule as Triggered in registry
   *   2. Mark rule as Proving in registry
   *   3. Encrypt transfer params for Arcium MXE
   *   4. Submit proof + queue Arcium computation in one tx
   *   5. Wait for Arcium callback to finalize
   */
  async submit(rule: ActiveRule, proof: GeneratedProof): Promise<string> {
    logger.info("Submitting proof to Solana...", { ruleId: rule.ruleId });

    const ruleIdBytes = Buffer.from(rule.ruleId.replace("0x", ""), "hex");

    // ── 1. Derive rule PDA ─────────────────────────────────────────────
    const ownerPubkey = new PublicKey(rule.owner);
    const [rulePda] = PublicKey.findProgramAddressSync(
      [Buffer.from("prova_rule"), ownerPubkey.toBytes(), ruleIdBytes],
      this.registryProgram.programId,
    );

    // ── 2. Mark triggered (monitor is a trusted signer) ────────────────
    await this.markTriggered(rulePda, proof.publicInputs.blockNumber);

    // ── 3. Mark proving ────────────────────────────────────────────────
    await this.markProving(rulePda);

    // ── 4. Encrypt transfer params for Arcium ──────────────────────────
    const { encryptedAmount, encryptedRecipient, pubKey, nonce } =
      await this.encryptForArcium(rule);

    // ── 5. Submit proof + queue Arcium computation ─────────────────────
    const computationOffset = new anchor.BN(randomBytes(8), "hex");
    const txSig = await this.submitProof(
      rule,
      rulePda,
      proof,
      ruleIdBytes,
      computationOffset,
      encryptedAmount,
      encryptedRecipient,
      pubKey,
      nonce,
    );

    logger.info("Proof submitted", { txSig });

    // ── 6. Await Arcium MXE computation finalization ───────────────────
    logger.info("Waiting for Arcium MXE to finalize...");
    const finalizeSig = await awaitComputationFinalization(
      this.provider as any,
      computationOffset,
      this.executorProgram.programId,
      "confirmed",
    );

    logger.info("✓ Arcium computation finalized", { finalizeSig });
    return finalizeSig;
  }

  private async markTriggered(
    rulePda: PublicKey,
    blockNumber: number,
  ): Promise<void> {
    try {
      const sig = await this.registryProgram.methods
        .markTriggered(new anchor.BN(blockNumber))
        .accounts({
          rule: rulePda,
          monitor: this.monitorKeypair.publicKey,
        })
        .signers([this.monitorKeypair])
        .rpc();
      logger.info("Rule marked as Triggered", { sig });
    } catch (err) {
      logger.error("markTriggered failed", { error: String(err) });
      throw err;
    }
  }

  private async markProving(rulePda: PublicKey): Promise<void> {
    const sig = await this.registryProgram.methods
      .markProving()
      .accounts({
        rule: rulePda,
        monitor: this.monitorKeypair.publicKey,
      })
      .signers([this.monitorKeypair])
      .rpc();
    logger.info("Rule marked as Proving", { sig });
  }

  /**
   * Encrypt the transfer parameters using Arcium's x25519 + RescueCipher.
   * This is what keeps the transfer amount and recipient private
   * from all Arcium nodes during MPC execution.
   */
  private async encryptForArcium(rule: ActiveRule): Promise<{
    encryptedAmount: Uint8Array;
    encryptedRecipient: Uint8Array;
    pubKey: Uint8Array;
    nonce: anchor.BN;
  }> {
    // Fetch the MXE's x25519 public key
    const mxePublicKey = await getMXEPublicKey(
      this.provider as any,
      this.executorProgram.programId,
    );

    if (!mxePublicKey) {
      throw new Error("Failed to fetch MXE public key");
    }

    // Generate ephemeral x25519 key pair
    const privateKey = x25519.utils.randomSecretKey();
    const pubKey = x25519.getPublicKey(privateKey);
    const sharedSecret = x25519.getSharedSecret(privateKey, mxePublicKey);

    const nonceBuf = randomBytes(16);
    const cipher = new RescueCipher(sharedSecret);

    // Encode recipient as lower 8 bytes of pubkey (just a tag for MPC validation)
    const recipientBytes = new PublicKey(rule.recipient).toBytes();
    const recipientTag = BigInt(
      "0x" + Buffer.from(recipientBytes.slice(0, 8)).toString("hex"),
    );

    // Encrypt [amount, recipient_tag]
    const ciphertext = cipher.encrypt(
      [BigInt(rule.actionAmount.toString()), recipientTag],
      nonceBuf,
    );

    return {
      encryptedAmount: new Uint8Array(ciphertext[0]),
      encryptedRecipient: new Uint8Array(ciphertext[1]),
      pubKey: pubKey,
      nonce: new anchor.BN(deserializeLE(nonceBuf).toString()),
    };
  }

  private async submitProof(
    rule: ActiveRule,
    rulePda: PublicKey,
    proof: GeneratedProof,
    ruleIdBytes: Buffer,
    computationOffset: anchor.BN,
    encryptedAmount: Uint8Array,
    encryptedRecipient: Uint8Array,
    pubKey: Uint8Array,
    nonce: anchor.BN,
  ): Promise<string> {
    // Derive vault PDA
    const tokenMint = new PublicKey(rule.tokenMint);
    const [vaultTokenAccount] = PublicKey.findProgramAddressSync(
      [Buffer.from("prova_vault"), tokenMint.toBytes()],
      this.executorProgram.programId,
    );
    const [vaultAuthority] = PublicKey.findProgramAddressSync(
      [Buffer.from("prova_vault")],
      this.executorProgram.programId,
    );

    // Derive pending execution PDA
    const [pendingExecution] = PublicKey.findProgramAddressSync(
      [Buffer.from("pending_exec"), ruleIdBytes],
      this.executorProgram.programId,
    );

    const recipientPubkey = new PublicKey(rule.recipient);
    const recipientTokenAccount = await this.getOrCreateATA(
      recipientPubkey,
      tokenMint,
    );

    // Encode public inputs for Solana
    const publicInputsEncoded = this.encodePublicInputs(proof);

    const arciumEnv = getArciumEnv();

    const sig = await (this.executorProgram.methods as any)
      .submitProofAndExecute(
        Array.from(proof.proofBytes),
        publicInputsEncoded,
        computationOffset,
        Array.from(encryptedAmount),
        Array.from(encryptedRecipient),
        Array.from(pubKey),
        nonce,
      )
      .accountsPartial({
        feePayer: this.monitorKeypair.publicKey,
        rule: rulePda,
        pendingExecution,
        vaultTokenAccount,
        vaultAuthority,
        recipientTokenAccount,
        tokenMint,
        computationAccount: this.deriveCompPda(computationOffset, arciumEnv),
        clusterAccount: this.deriveClusterPda(arciumEnv),
        mxeAccount: this.deriveMxePda(),
        mempoolAccount: this.deriveMempoolPda(arciumEnv),
        executingPool: this.deriveExecPoolPda(arciumEnv),
        compDefAccount: this.deriveCompDefPda(),
        poolAccount: arciumEnv.feePoolAccount,
        clockAccount: arciumEnv.clockAccount,
        systemProgram: SystemProgram.programId,
      })
      .signers([this.monitorKeypair])
      .rpc({ commitment: "confirmed" });

    return sig;
  }

  private encodePublicInputs(proof: GeneratedProof): object {
    const pi = proof.publicInputs;
    return {
      blockNumber: new anchor.BN(pi.blockNumber),
      stateRoot: Array.from(Buffer.from(pi.stateRoot.replace("0x", ""), "hex")),
      walletAddress: Array.from(
        Buffer.from(pi.walletAddress.replace("0x", ""), "hex"),
      ),
      thresholdWei: Array.from(
        Buffer.from(pi.thresholdWei.replace("0x", "").padStart(64, "0"), "hex"),
      ),
      ruleId: Array.from(Buffer.from(pi.ruleId.replace("0x", ""), "hex")),
    };
  }

  private async getOrCreateATA(
    owner: PublicKey,
    mint: PublicKey,
  ): Promise<PublicKey> {
    const { getAssociatedTokenAddress } = await import("@solana/spl-token");
    return getAssociatedTokenAddress(mint, owner);
  }

  // ── Arcium PDA derivations (mirrors the Rust macros) ─────────────────
  private deriveMxePda(): PublicKey {
    const [pda] = PublicKey.findProgramAddressSync(
      [Buffer.from("mxe")],
      this.executorProgram.programId,
    );
    return pda;
  }
  private deriveClusterPda(env: any): PublicKey {
    return env.arciumClusterAccount ?? this.deriveMxePda();
  }
  private deriveMempoolPda(env: any): PublicKey {
    return env.mempoolAccount ?? this.deriveMxePda();
  }
  private deriveExecPoolPda(env: any): PublicKey {
    return env.executingPoolAccount ?? this.deriveMxePda();
  }
  private deriveCompPda(offset: anchor.BN, env: any): PublicKey {
    const [pda] = PublicKey.findProgramAddressSync(
      [Buffer.from("comp"), offset.toArrayLike(Buffer, "le", 8)],
      new PublicKey(config.executorProgramId),
    );
    return pda;
  }
  private deriveCompDefPda(): PublicKey {
    // comp_def_offset("execute_transfer") — must match the Rust constant
    const offsetBuf = Buffer.alloc(4);
    offsetBuf.writeUInt32LE(0x1234abcd); // placeholder — replace with actual value
    const [pda] = PublicKey.findProgramAddressSync(
      [Buffer.from("comp_def"), offsetBuf],
      new PublicKey(config.executorProgramId),
    );
    return pda;
  }
}
