[package]
name    = "prova_executor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name       = "prova_executor"

[dependencies]
anchor-lang   = { workspace = true }
anchor-spl    = { workspace = true }
arcium-anchor = { workspace = true }
sp1-solana    = { workspace = true }
borsh         = { workspace = true }